### ISSUE TITLE
Double cars

### ISSUE THREAD

**Issue by Rassez** [enc0ded/enc0ded-persistent-vehicles#3]
I saved cars around map. For some reason first registered car spawn to some other car. Check video. I saved cars, restarted server and then this happen. [VIDEO]

https://streamable.com/ncrv32

**Comment by enc0ded** [comment]
Can you update to the latest version and try again.

**Comment by Rassez** [comment]
Yeah i tried, but nothing. Exactly same happen, It doesn't matter by car.

**Comment by iSentrie** [comment]
have you wiped saved vehicles before trying again?

**Comment by Rassez** [comment]
Yep. I tried wipe vehicles. We use onesync infinity, can it cause that maybe?

**Comment by enc0ded** [comment]
Maybe I've not tried it on infinity. This probably has something to do with getting entity serverside. 

Once this https://github.com/citizenfx/natives/issues/315 issue is resolved I will have a fix because I'll be able to use the plate to fetch the entity meaning there will never be a chance for a duplicate to spawn.

**Comment by enc0ded** [comment]
Fixed: https://github.com/enc0ded/enc0ded-persistent-vehicles/commit/51bd8d31a132e2a8cada5374f10c1ff5f8a69452
